### ISSUE TITLE
Error when trying to eval

### ISSUE THREAD

**Issue by rajaravivarma-r** [python-mario/mario#165]
I am facing this error when trying out the example in the docs.
```
user@path : mario eval 1+1
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.7.3/bin/mario", line 10, in <module>
    sys.exit(cli())
  File "/Users/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/click/core.py", line 1164, in invoke
    return _process_result(rv)
  File "/Users/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/click/core.py", line 1102, in _process_result
    **ctx.params)
  File "/Users/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mario/cli.py", line 174, in cli_main
    app.main(pairs, **kwargs)
  File "/Users/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mario/app.py", line 112, in main
    trio.run(functools.partial(async_main, pairs, **kwargs))
  File "/Users/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/trio/_core/_run.py", line 1783, in run
    raise runner.main_task_outcome.error
  File "/Users/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mario/app.py", line 61, in async_main
    stream = trio._unix_pipes.PipeReceiveStream(os.dup(0))
AttributeError: module 'trio._unix_pipes' has no attribute 'PipeReceiveStream'
```

**Comment by rajaravivarma-r** [comment]
Thanks, that fixes the problem :). I will close this issue.
