### ISSUE TITLE
Getting a  ValueError("incomplete frame") with the read-json operation

### ISSUE THREAD

**Issue by halloleo** [python-mario/mario#290]
Given a JSON file `addrx.json`  I get when calling mario like this

    cat addrx.json  | mario read-json 

the following traceback

```
Traceback (most recent call last):
  File "/home/me/opt/pipx/bin/mario", line 8, in <module>
    sys.exit(cli())
  File "/home/me/opt/pipx/venvs/mario/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/me/opt/pipx/venvs/mario/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/me/opt/pipx/venvs/mario/lib/python3.7/site-packages/click/core.py", line 1164, in invoke
    return _process_result(rv)
  File "/home/me/opt/pipx/venvs/mario/lib/python3.7/site-packages/click/core.py", line 1102, in _process_result
    **ctx.params)
  File "/home/me/opt/pipx/venvs/mario/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/me/opt/pipx/venvs/mario/lib/python3.7/site-packages/mario/cli.py", line 161, in cli_main
    app.main(pairs, **kwargs)
  File "/home/me/opt/pipx/venvs/mario/lib/python3.7/site-packages/mario/app.py", line 113, in main
    trio.run(functools.partial(async_main, pairs, **kwargs))
  File "/home/me/opt/pipx/venvs/mario/lib/python3.7/site-packages/trio/_core/_run.py", line 1444, in run
    raise runner.main_task_outcome.error
  File "/home/me/opt/pipx/venvs/mario/lib/python3.7/site-packages/mario/app.py", line 105, in async_main
    stack, items = await program_runner(traversals, items, global_context)
  File "/home/me/opt/pipx/venvs/mario/lib/python3.7/site-packages/mario/app.py", line 54, in program_runner
    items = await call_traversal(context, traversal, items, stack)
  File "/home/me/opt/pipx/venvs/mario/lib/python3.7/site-packages/mario/app.py", line 44, in call_traversal
    return await traversal.plugin_object.traversal_function(**args)
  File "/home/me/opt/pipx/venvs/mario/lib/python3.7/site-packages/mario/plugins/basic.py", line 239, in apply
    return traversals.AsyncIterableWrapper([await function([x async for x in items])])
  File "/home/me/opt/pipx/venvs/mario/lib/python3.7/site-packages/mario/plugins/basic.py", line 239, in <listcomp>
    return traversals.AsyncIterableWrapper([await function([x async for x in items])])
  File "/home/me/opt/pipx/venvs/mario/lib/python3.7/site-packages/mario/app.py", line 103, in <genexpr>
    items = (item.decode() async for item in receiver)
  File "/home/me/opt/pipx/venvs/mario/lib/python3.7/site-packages/mario/asynch.py", line 82, in __anext__
    return await self.receive()
  File "/home/me/opt/pipx/venvs/mario/lib/python3.7/site-packages/mario/asynch.py", line 64, in receive
    raise ValueError("incomplete frame")
```

Happy to upload the (smallish) file `addrx.json` to somewhere  to make this issue reproducible.  

### Side note

When I feed the input file first through `jq` for pretty-printing like this 

    cat addrx.json | jq . | mario read-json 

mario returns  the expected result.

**Comment by halloleo** [comment]
Here you go: Download it from [here](http://www.halloleo.net/etc/forums/mario-issue/addrx.json).

**Comment by halloleo** [comment]
Also I can confirm the issue happens on CentOS 6 (with 3.7.4) and macOS High Sierra (with 3.7.6), so it is less likely an installation issue.

**Comment by halloleo** [comment]
Thanks for looking into this. 

Just thinking: jq can read it - and even Python's json.load can read it...

But I agree, a better error message pointing the user towards how to fix it, would definitely help.
